//
//  CurrencyModel.swift
//  Debt Tracker
//
//  Created by Caner Çağrı on 13.02.2023.
//

import Foundation

struct CurrenyData {
    
    static let currencyData: [(name: String, symbol: String, ISO: String)] = [
        ("Afghan Afghani", "AFN", "؋"),
        ("Albanian Lek", "ALL", "L"),
        ("Algerian Dinar", "DZD", "د.ج"),
        ("Argentine Peso", "ARS", "$"),
        ("Armenian Dram", "AMD", "֏"),
        ("Australian Dollar", "AUD", "$"),
        ("Azerbaijani Manat", "AZN", "₼"),
        ("Bahamian Dollar", "BSD", "$"),
        ("Bahraini Dinar", "BHD", ".د.ب"),
        ("Bangladeshi Taka", "BDT", "৳"),
        ("Barbadian Dollar", "BBD", "$"),
        ("Belarusian Ruble", "BYN", "Br"),
        ("Belize Dollar", "BZD", "BZ$"),
        ("Bermudian Dollar", "BMD", "$"),
        ("Bhutanese Ngultrum", "BTN", "Nu."),
        ("Bolivian Boliviano", "BOB", "Bs."),
        ("Bosnia and Herzegovina Convertible Mark", "BAM", "KM"),
        ("Botswanan Pula", "BWP", "P"),
        ("Brazilian Real", "BRL", "R$"),
        ("British Pound Sterling", "GBP", "£"),
        ("Brunei Dollar", "BND", "$"),
        ("Bulgarian Lev", "BGN", "лв"),
        ("Burundian Franc", "BIF", "Fr"),
        ("Cambodian Riel", "KHR", "៛"),
        ("Canadian Dollar", "CAD", "$"),
        ("Cape Verdean Escudo", "CVE", "$"),
        ("Cayman Islands Dollar", "KYD", "$"),
        ("Central African CFA Franc", "XAF", "Fr"),
        ("Chilean Peso", "CLP", "$"),
        ("Chinese Yuan", "CNY", "¥"),
        ("Colombian Peso", "COP", "$"),
        ("Comorian Franc", "KMF", "Fr"),
        ("Congolese Franc", "CDF", "Fr"),
        ("Costa Rican Colón", "CRC", "₡"),
        ("Croatian Kuna", "HRK", "kn"),
        ("Cuban Convertible Peso", "CUC", "$"),
        ("Cuban Peso", "CUP", "$"),
        ("Czech Koruna", "CZK", "Kč"),
        ("Danish Krone", "DKK", "kr"),
        ("Djiboutian Franc", "DJF", "Fr"),
        ("Dominican Peso", "DOP", "RD$"),
        ("East Caribbean Dollar", "XCD", "$"),
        ("Egyptian Pound", "EGP", "£"),
        ("Eritrean Nakfa", "ERN", "Nfk"),
        ("Ethiopian Birr", "ETB", "Br"),
        ("Euro", "EUR", "€"),
        ("Fiji Dollar", "FJD", "$"),
        ("Gambian Dalasi", "GMD", "D"),
        ("Georgian Lari", "GEL", "₾"),
        ("Ghanaian Cedi", "GHS", "GH₵"),
        ("Gibraltar Pound", "GIP", "£"),
        ("Guatemalan Quetzal", "GTQ", "Q"),
        ("Guinean Franc", "GNF", "Fr"),
        ("Guyanese Dollar", "GYD", "$"),
        ("Haitian Gourde", "HTG", "G"),
        ("Honduran Lempira", "HNL", "L"),
        ("Hong Kong Dollar", "HKD", "$"),
        ("Hungarian Forint", "HUF", "Ft"),
        ("Icelandic Króna", "ISK", "kr"),
        ("Indian Rupee", "INR", "₹"),
        ("Indonesian Rupiah", "IDR", "Rp"),
        ("Iranian Rial", "IRR", "﷼"),
        ("Iraqi Dinar", "IQD", "ع.د"),
        ("Israeli New Shekel", "ILS", "₪"),
        ("Jamaican Dollar", "JMD", "$"),
        ("Japanese Yen", "JPY", "¥"),
        ("Jordanian Dinar", "JOD", "د.ا"),
        ("Kazakhstani Tenge", "KZT", "₸"),
        ("Kenyan Shilling", "KES", "KSh"),
        ("Kuwaiti Dinar", "KWD", "د.ك"),
        ("Kyrgyzstani Som", "KGS", "с"),
        ("Lao Kip", "LAK", "₭"),
        ("Latvian Lats", "LVL", "Ls"),
        ("Lebanese Pound", "LBP", "£"),
        ("Lesotho Loti", "LSL", "L"),
        ("Liberian Dollar", "LRD", "$"),
        ("Libyan Dinar", "LYD", "ل.د"),
        ("Macanese Pataca", "MOP", "P"),
        ("Macedonian Denar", "MKD", "ден"),
        ("Malagasy Ariary", "MGA", "Ar"),
        ("Malawian Kwacha", "MWK", "MK"),
        ("Malaysian Ringgit", "MYR", "RM"),
        ("Maldivian Rufiyaa", "MVR", "ރ."),
        ("Mauritanian Ouguiya", "MRU", "UM"),
        ("Mauritian Rupee", "MUR", "₨"),
        ("Mexican Peso", "MXN", "$"),
        ("Moldovan Leu", "MDL", "L"),
        ("Mongolian Tugrik", "MNT", "₮"),
        ("Moroccan Dirham", "MAD", "د.م."),
        ("Mozambican Metical", "MZN", "MT"),
        ("Myanmar Kyat", "MMK", "K"),
        ("Namibian Dollar", "NAD", "$"),
        ("Nepalese Rupee", "NPR", "₨"),
        ("Netherlands Antillean Guilder", "ANG", "ƒ"),
        ("New Zealand Dollar", "NZD", "$"),
        ("Nicaraguan Córdoba", "NIO", "C$"),
        ("Nigerian Naira", "NGN", "₦"),
        ("North Korean Won", "KPW", "₩"),
        ("Norwegian Krone", "NOK", "kr"),
        ("Omani Rial", "OMR", "﷼"),
        ("Pakistani Rupee", "PKR", "₨"),
        ("Panamanian Balboa", "PAB", "B/."),
        ("Papua New Guinean Kina", "PGK", "K"),
        ("Paraguayan Guarani", "PYG", "₲"),
        ("Peruvian Sol", "PEN", "S/."),
        ("Philippine Peso", "PHP", "₱"),
        ("Polish Zloty", "PLN", "zł"),
        ("Qatari Riyal", "QAR", "﷼"),
        ("Romanian Leu", "RON", "L"),
        ("Russian Ruble", "RUB", "₽"),
        ("Rwandan Franc", "RWF", "Fr"),
        ("Saint Helenian Pound", "SHP", "£"),
        ("Salvadoran Colón", "SVC", "$"),
        ("Samoan Tala", "WST", "T"),
        ("Sao Tomean Dobra", "STD", "Db"),
        ("Saudi Arabian Riyal", "SAR", "﷼"),
        ("Serbian Dinar", "RSD", "дин."),
        ("Seychellois Rupee", "SCR", "₨"),
        ("Sierra Leonean Leone", "SLL", "Le"),
        ("Singapore Dollar", "SGD", "$"),
        ("Solomon Islands Dollar", "SBD", "$"),
        ("Somali Shilling", "SOS", "Sh"),
        ("South African Rand", "ZAR", "R"),
        ("South Korean Won", "KRW", "₩"),
        ("South Sudanese Pound", "SSP", "£"),
        ("Sri Lankan Rupee", "LKR", "₨"),
        ("Sudanese Pound", "SDG", "£"),
        ("Surinamese Dollar", "SRD", "$"),
        ("Swazi Lilangeni", "SZL", "L"),
        ("Swedish Krona", "SEK", "kr"),
        ("Swiss Franc", "CHF", "Fr"),
        ("Syrian Pound", "SYP", "£"),
        ("Taiwan New Dollar", "TWD", "$"),
        ("Tajikistani Somoni", "TJS", "SM"),
        ("Tanzanian Shilling", "TZS", "Sh"),
        ("Thai Baht", "THB", "฿"),
        ("Tongan Pa'anga", "TOP", "T$"),
        ("Trinidad and Tobago Dollar", "TTD", "$"),
        ("Tunisian Dinar", "TND", "د.ت"),
        ("Turkish Lira", "TRY", "₺"),
        ("Turkmenistani Manat", "TMT", "m"),
        ("Tuvaluan Dollar", "TVD", "$"),
        ("Ugandan Shilling", "UGX", "Sh"),
        ("Ugandan Shilling", "UGX", "Sh"),
        ("Ukrainian Hryvnia", "UAH", "₴"),
        ("United Arab Emirates Dirham", "AED", "د.إ"),
        ("United States Dollar", "USD", "$"),
        ("Uruguayan Peso", "UYU", "$"),
        ("Uzbekistani Som", "UZS", "лв"),
        ("Vanuatu Vatu", "VUV", "Vt"),
        ("Venezuelan Bolívar", "VES", "Bs"),
        ("Vietnamese Dong", "VND", "₫"),
        ("West African CFA franc", "XOF", "Fr"),
        ("Yemeni Rial", "YER", "﷼"),
        ("Zambian Kwacha", "ZMW", "ZK"),
        ("Zimbabwean Dollar", "ZWL", "$")
    ]
}

